language: rust
sudo: required
dist: xenial
rust:
  - stable
  - beta
  - nightly
script:
  - cargo build --verbose --all --all-features
  - env RUST_BACKTRACE=1 cargo test --verbose --all --all-features
  - env RUST_BACKTRACE=1 cargo test --verbose --all --no-default-features
